package sk.upjs.ics.presov.opendata;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.net.Uri;
import android.os.Bundle;

public class Defaults {

    public static final String XML_PARSER_INPUT_ENCODING = null;

    public static final SQLiteDatabase.CursorFactory DEFAULT_CURSOR_FACTORY = null;

    public static final String NO_NULL_COLUMN_HACK = null;

    public static final String AUTOGENERATED_ID = null;

    public static final String NO_ARGUMENTS = null;

    public static final String NO_TYPE = null;

    public static final Uri NO_URI = null;

    public static final Bundle NO_BUNDLE = null;

    public static final Cursor NO_CURSOR = null;

    public static final String NO_DATE = null;

    public static final Object NO_COOKIE = null;

    public static final int NO_FLAGS = 0;

    public static final String[] ALL_COLUMNS = null;

    public static final String[] ALL_COLUMNS_WITH_ROWID = {"rowid", "*"};

    public static final String NO_SELECTION = null;

    public static final String[] NO_SELECTION_ARGS = null;

    public static final String NO_GROUP_BY = null;

    public static final String NO_HAVING = null;

    public static final String NO_STRING_URL = null;

    public static final int SPINNER_DEFAULT_DATASET_INFO_ID = -1;

    public static final String DATASET_ID = "dataset_id";

    public static final String COLUMN_PREFERENCE_DEFAULT_VALUE = "col_0";

    public static final String SHARED_PREFERENCES_DATASET_INFO = "preferences_dataset_info";

    public static final String DATE_PREFERENCE_DEFAULT_VALUE = null;

    public static final int DEFAULT_COLUMN_VALUE = 0;

    public static final String COLUMN_PREFIX = "col_";
}
